name: Build and test

on:
  push:
    branches: [ "dev", "main", "indexing", "release/**" ]
    paths-ignore:
      - '**.md'
      - 'fastlane/**'
      - '.github/workflows/crowdin_contributors.yml'
  pull_request:
    branches: [ "dev" ]
    paths-ignore:
      - '**.md'
      - 'fastlane/**'
      - '.github/workflows/crowdin_contributors.yml'
  workflow_dispatch: { }

env:
  # Misc
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Signing info (empty on forks, debug key is used then)
  IDE_SIGNING_ALIAS: ${{ secrets.IDE_SIGNING_ALIAS }}
  IDE_SIGNING_AUTH_PASS: ${{ secrets.IDE_SIGNING_AUTH_PASS }}
  IDE_SIGNING_AUTH_USER: ${{ secrets.IDE_SIGNING_AUTH_USER }}
  IDE_SIGNING_KEY_PASS: ${{ secrets.IDE_SIGNING_KEY_PASS }}
  IDE_SIGNING_STORE_PASS: ${{ secrets.IDE_SIGNING_STORE_PASS }}
  IDE_SIGNING_URL: ${{ secrets.IDE_SIGNING_URL }}
  IDE_SIGNING_KEY_BIN: ${{ secrets.IDE_SIGNING_KEY_BIN }}

  # Build configuration
  BUILD_JAVA_VERSION: '17'
  BUILD_JAVA_DIST: 'adopt'
  BUILD_IS_RELEASE: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release/**' }}
  ReleaseAndroidIDE: ${{ github.ref == 'refs/heads/main' }}

jobs:
  build_apk:
    strategy:
      # Do not cancel the other build type if one of them fails
      fail-fast: false
      matrix:
        build_type: ['debug', 'release']
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.BUILD_JAVA_VERSION }}
          distribution: ${{ env.BUILD_JAVA_DIST }}
      - name: Change Gradle wrapper permissions
        run: chmod +x ./gradlew
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Create debug keystore
        run: |
          mkdir -p ~/.android
          rm -f ~/.android/debug.keystore
          keytool -genkeypair -keystore ~/.android/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
      - name: Assemble ${{ matrix.build_type }} APK
        run: |
          build_type=${{ matrix.build_type }}
          ./gradlew :core:app:assemble${build_type^}
      - name: Copy ${{ matrix.build_type }} APK
        run: |
          cp core/app/build/outputs/apk/${{ matrix.build_type }}/app-*.apk ./
      - name: Upload arm64-v8a ${{ matrix.build_type }} APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-arm64-v8a-${{ matrix.build_type }}
          path: app-arm64-v8a-${{ matrix.build_type }}.apk
      - name: Upload armeabi-v7a ${{ matrix.build_type }} APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-armeabi-v7a-${{ matrix.build_type }}
          path: app-armeabi-v7a-${{ matrix.build_type }}.apk
      - name: Upload x86_64 ${{ matrix.build_type }} APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-x86_64-${{ matrix.build_type }}
          path: app-x86_64-${{ matrix.build_type }}.apk
